
export interface CreateTicketRequest {
  serviceId: number;    //customer has only to select the service type
}

//minimum input from the customer for security reasons
//all other data are generated by the system

export interface CreateTicketResponse {
  ticket: {
    id: number;
    code: string;
    service: {
      id: number;
      tag: string;
      name: string;
    };
    queueLength: number;
    positionInQueue: number;
    createdAt: Date;
  };
  queueInfo: {
    serviceId: number;
    queueLength: number;
  };
}

export interface ServiceTypeResponse {
  id: number;
  tag: string;
  name: string;
}