
export interface CreateTicketRequest {
  serviceTypeId: string;    //customer has only to select the service type
}

//minimum input from the customer for security reasons
//all other data are generated by the system

export interface CreateTicketResponse {
  ticket: {
    id: string;
    ticketCode: string;
    serviceType: {
      id: string;
      tag: string;
      name: string;
    };
    queueLength: number;
    positionInQueue: number;
    createdAt: Date;
  };
  queueInfo: {
    serviceTypeId: string;
    queueLength: number;
  };
}

export interface ServiceTypeResponse {
  id: string;
  tag: string;
  name: string;
}